server:
  port: 9999
  servlet:
    context-path: /MP-quickstart

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
# DataSource Config
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      #基本属性
      url: jdbc:mysql://localhost:3308/demo?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: 123456
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接密码（默认为空）
    password:
    # Redis服务器连接端口
    port: 6379
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 30000
      

# Logger Config
logging:
  level:
    com.yjp.mybatisplus.mapper: debug
   
# MyBatis xml文件配置 
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      logic-delete-value: N # 逻辑已删除值(默认为 1)
      logic-not-delete-value: Y # 逻辑未删除值(默认为 0)

demo:
  phone: 13918738971
  wife: zhaosiwen




